title: LeagueTV
description: "Watch League of Legend's LCS matches live and on demand!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://league-tv.hamstercat.com" # the base hostname & protocol for your site

exclude: ['node_modules', 'gulpfile.js', 'package.json', '.settings', 'README.md', 'CNAME', 'issue_template.md']
assets:
  sources:
    - fonts
    - images
